#pass in params/input
#pass out params/input
on:
  workflow_call:
    inputs:
      csproj:
        required: true
        type: string
      hd_num:
        required: true
        type: string

jobs:
  build-mobile:
    runs-on: windows-latest

    steps:
      - name: Echo env
        shell: pwsh
        run: |
          echo "this is from called action workflow folder"
          pwd
          echo "${{inputs.csproj}}"
          echo "${{ inputs.csproj }}"
          echo "----------------"
          echo "${{inputs.hd_num}}"
          echo "${{ inputs.hd_num }}"
