on:
  workflow_call:
    inputs:
      csproj:
        required: true
        type: string
      hd_num:
        required: true
        type: string

jobs:
  build-mobile:
    runs-on: windows-latest

    steps:
      - name: Echo env
        shell: pwsh
        run: |
          echo "this is from called action workflow folder"
          pwd
          echo "${{inputs.csproj}}"
          echo "${{ inputs.csproj }}"
          echo "----------------"
          echo "${{inputs.hd_num}}"
          echo "${{ inputs.hd_num }}"

      # - uses: actions/checkout@v2

      # - name: Show Files
      #   run: |
      #     pwd
      #     ls

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v2
      #   with:
      #     dotnet-version: 7.0.x
      #     include-prerelease: true

      # - name: Install MAUI Workloads
      #   run: |
      #     dotnet workload install maui --source https://api.nuget.org/v3/index.json          

      # - name: Build MAUI Mobile app
      #   shell: pwsh
      #   run: |
      #     dotnet build ${{inputs.csproj}} -bl:mobile.binlog

      # - name: Archive build log
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: logs
      #     path: '*.binlog'
